spring:
  application:
    name: EurekaServer
  boot:
    admin:
      context-path: /admin
      ui:
        title: "Eureka Server and Admin"

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"