server:
    port: 8088

spring:
    application:
        name: inventory-service
    datasource:
        driver: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/InventoryDB?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: sathishvarunt@gmail.com
        password: yvgtppuikqesyidz
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
    banner:
        location: classpath:banner.txt
    boot:
        admin:
            client:
                url: http://localhost:8761/admin
                enabled: true
                instance:
                    service-url: http://localhost:8088
eureka:
    instance:
        hostname: ${vcap.application.uris[0]:localhost}
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
        leaseRenewalIntervalInSeconds: 5
    client:
        region: default
        service-url:
            defaultZone: http://localhost:8761/eureka/

management:
    info:
        env:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"

info:
    app:
        name: Inventory Management Rest API
        version: 1.0.0
        description: Inventory Management Rest API