spring:
    application:
        name: inventory-service
    datasource:
        url: jdbc:mysql://localhost:3306/InventoryDB?createDatabaseIfNotExist=true
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
        ddl-auto: update
        show-sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: sathishvarunt@gmail.com
        password: yvgtppuikqesyidz
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000

server:
    port: 8088
eureka:
    instance:
        hostname: ${vcap.application.uris[0]:localhost}
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
        leaseRenewalIntervalInSeconds: 5
    client:
        region: default
