server:
    port: 8082

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${server.port}

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOrigins: "http://localhost:4200"
                        allowedMethods:
                            - GET
                            - POST
                            - DELETE
                            - PATCH
            routes:
                -   id: book-service
                    uri: lb://BOOK-SERVICE
                    predicates:
                        - Path=/dbs/books/**
                -   id: user-service
                    uri: lb://USER-SERVICE
                    predicates:
                        - Path=/dbs/user/**
                -   id: order-service
                    uri: lb://ORDER-SERVICE
                    predicates:
                        - Path=/dbs/order/**
                -   id: inventory-service
                    uri: lb://INVENTORY-SERVICE
                    predicates:
                        - Path=/dbs/inventory/**
                -   id: review-service
                    uri: lb://REVIEW-SERVICE
                    predicates:
                        - Path=/dbs/review/**