server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-MODULE
          predicates:
            - Path=/users/**
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/dbs/books/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/dbs/review/**