server:
  port: 8082

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PATCH
              - PUT
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/dbs/user/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/dbs/books/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/dbs/order/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/dbs/inventory/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/dbs/review/**
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

  logging:
    level:
      org.springframework.cloud.gateway: TRACE
      org.springframework.web.reactive.filter.ForwardingFilter: TRACE
      org.springframework.web.server.WebFilter: TRACE
      com.project.gateway.filter: DEBUG