server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/digital_bookstore?createDatabaseIfNotExist=true
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

## Eureka Client
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
## Feign Client
#feign.client.config.default.connectTimeout=5000
#feign.client.config.default.readTimeout=5000

 


eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5

  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

